update loading icon and spelling issues.
HyperiumClient/Old-Installer pull request #7
Opened 2018-07-17 14:33 UTC by MODKILLER1001

2018-07-17 15:38 UTC, Cubxity requested changes
Bland.

2018-07-17 17:47 UTC, MODKILLER1001 commented
git -merge

2018-07-17 17:48 UTC, Cubxity commented
No. I don't like the icon

2018-07-17 20:15 UTC, RDIL approved these changes

2018-09-11 07:12 UTC, ChachyGit commented
is anyone going to close this?

2018-09-27 04:53 UTC, closed without merging